### ISSUE TITLE
Ways to collaborate 

### ISSUE THREAD

**Issue by nricklin** [kostasthebarbarian/gbdxtools#11]
Love the refactoring and all the work going into gbdxtools.

What do you guys think about using issues as a way to keep organized and know what's going on in the project?  

Let's write issues about the functionality we want to add, link pull requests to the issues, and then PR them into dev when ready.

**Comment by kostasthebarbarian** [comment]
Sounds good.
To start with, can we add some simple instructions on how to use IDAHO in the user guide?
It's the only thing missing from there at the moment.

**Comment by kostasthebarbarian** [comment]
We all agree. I moved all issues from the Tomnod trello board here. It makes more sense to have ongoing developments here.
