### ISSUE TITLE
We need unit tests that cover everything

### ISSUE THREAD

**Issue by nricklin** [kostasthebarbarian/gbdxtools#12]
As more and more of us work on this, we need to have solid unit test coverage so that we can keep confidence that nothing is breaking along the way.

The crux is that we've got to stub the connections and responses to auth & gbdx apis, but in a way that is easy to add more unit tests and modify existing unit tests, and without running tests on just the stubs.

**Comment by kostasthebarbarian** [comment]
I am getting errors when trying to run the tests:
E           WheelError: Install wheel[signatures] (requires keyring, pyxdg) for signatures.

I tried defining the venv both inside and outside the project directory but I still get errors.

**Comment by nricklin** [comment]
k.  let's start that up as a separate issue.
